import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Witamy w inscenizacji DOCUMENT CHECKER</h1>
      </main>

      <footer className={styles.footer}>
        <small>&copy; Copyright 2022, Document-checker team</small>
      </footer>
    </div>
  );
}
